### ISSUE TITLE
[2.0.0] New version adapted for OctoBot v0.4.0

### ISSUE THREAD

**Issue by Herklos** [Drakkar-Software/OctoBot-Tentacles-Manager#8]
Reflections around :
- Architectural refactoring (I'm currently working on it)
- Added features
- Removed features

**Comment by Herklos** [comment]
[Tentacles-Manager-arch.drawio.zip](https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/files/4016853/Tentacles-Manager-arch.drawio.zip)

**Comment by GuillaumeDSM** [comment]
> First version : [Tentacles-Manager-arch.drawio.zip](https://github.com/Drakkar-Software/OctoBot-Tentacles-Manager/files/4016853/Tentacles-Manager-arch.drawio.zip)

![image](https://user-images.githubusercontent.com/9078616/75607743-979a0a00-5afa-11ea-8ea3-685a97611939.png)
